services:
  mariadb:
    image: mariadb:latest
    container_name: MariaDB-SI
    environment:
      MARIADB_ROOT_PASSWORD: rares
      MARIADB_DATABASE: SIproiect
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    container_name: Python-KMS
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    volumes:
      - ./src:/app

volumes:
  mariadb_data: